# Generated by Django 4.2 on 2023-05-10 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_event_custom_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='contact_name',
        ),
        migrations.AlterField(
            model_name='event',
            name='host',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_hosted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='bio',
            field=models.TextField(default='', max_length=100, null=True),
        ),
    ]
