# Generated by Django 4.2 on 2023-05-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_host_events_hosting_alter_event_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='host',
            new_name='orgsnizer',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
